config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root  'home#index'
  
  resources :home, only:[:index] do
    collection do
      get 'chat', 'other'
    end
  end

  resources :users, only:[:show]
  
  resources :tweets do
    member do
      get 'discussion'
    end
    resources :tweet_comments, only: [:create]
  end
  
  resources :items, only:[:index]
  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'シューズ' },
    { id: 3, name: 'バスケットウェアー'},
    { id: 4, name: 'ソックス'},
    { id: 5, name: 'トレーニングウェアー'},
    { id: 6, name: 'Bリーググッズ'},
    { id: 7, name: 'NBAグッズ'},
    { id: 8, name: 'レフリー'},
    { id: 9, name: 'ボール' },
    { id: 10, name: 'コート用品'},
    { id: 11, name: 'バッグ'},
    { id: 12, name: 'アクセサリー・グッズ'},
    { id: 13, name: 'インナーウェアー'},
    { id: 14, name: 'サポーター' },
    { id: 15, name: 'テーピング'},
    { id: 16, name: 'アイシンググッズ'},
    { id: 17, name: 'トレーニング用品'},
  ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
end

app/models/number_of_day.rb
class NumberOfDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1〜2日で発送' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '4〜7日で発送' }
  ]
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/sender_area.rb
class SenderArea < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品、未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '秋田ノーザンハピネッツ', image: 'image/about01_02.png' },
    { id: 3, name: '横浜ビー・コルセアーズ', image: 'image/fl_club_primary.png' },
    { id: 4, name: '新潟アルビレックスBB',image: 'image/img_flag.gif' },
    { id: 5, name: '富山グラウジーズ',image: 'image/富山.png' },
    { id: 6, name: 'レバンガ北海道',image: 'image/square_levanga_logo.png' },
    { id: 7, name: '宇都宮ブレックス',image: 'image/ph00162920.png' },
    { id: 8, name: '千葉ジェッツ',image: 'image/chibajets_logo_2018-01.png' },
    { id: 9, name: 'アルバルク東京',image: 'image/alvark.png' },
    { id: 10, name: 'サンロッカーズ渋谷',image: 'image/sr.png' },
    { id: 11, name: '川崎ブレイブサンダース',image: 'image/201807022050_2-600x0.png' },
    { id: 12, name: '三遠ネオフェニックス',image: 'image/_____________.png' },
    { id: 13, name: '滋賀レイクスターズ',image: 'image/logo.png' },
    { id: 14, name: '京都ハンナリーズ',image: 'image/京都.jpg' },
    { id: 15, name: '大阪エヴェッサ',image: 'image/8FEcLku_.png' },
    { id: 16, name: '琉球ゴールデンキングス',image: 'image/rg.png' },
    { id: 17, name: '信州ブレイブウォリアーズ',image: 'image/FPfXFwON_400x400.png' },
    { id: 18, name: '島根スサノオマジック',image: 'image/島根.jpeg' },
    { id: 19, name: '広島ドラゴンフライズ',image: 'image/広島.png' },
    { id: 20, name: 'シーホース三河',image: 'image/三河.png' },
    { id: 21, name: '名古屋ダイヤモンドドルフィンズ',image: 'image/team-logo01.png' },
    { id: 22, name: 'その他' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  has_one_attached :image
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy

  with_options presence: true do
    validates :name,   length: { maximum: 20 } 
    validates :image
    validates :text,   length: { maximum: 300 }    
    validates :team_id, numericality:{ other_than: 1, message: "を選択してください" }
  end

end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def remember_me
    true
  end
  
  has_many :items
  has_many :tweet_comments
  has_many :item_comments
  has_many :orders
  belongs_to_active_hash :team

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字混合で入力してください" }

  with_options presence: true do
    validates :nickname
    validates :phone, format: { with: /\A\d{10,11}\z/, message: "を半角数字のみ(10文字から11文字)で入力してください" }
    validates :full_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を全角で入力してください" }
    validates :full_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "を全角（カナ）で入力してください" }
    validates :birth_day
    validates :sex
    validates :team_id, numericality: { other_than: 1, message: "を選択してください" }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaskeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p:400,500" rel="stylesheet">
    <%= javascript_pack_tag 'application' %>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="card">
    <h6 class="card-header text-light bg-dark" style="border-bottom:2px solid white;">BaskeApp</h6>
    <div class="text-light bg-dark">
      COPYRIGHT © ZAB Inc. All rights Reserved.
    </div>
  </div>
</footer>

app/views/shared/_form.html.erb
<div class="d-flex flex-column" style="height: 500px; text-align: center;">

  <div class="my-3">
    <%= form.label :お題, class:"bg-dark text-white"%>
    <%= form.label :必須, class:"badge badge-danger" %><br/>
    <%= form.text_field :name, placeholder: "例）試合観戦", class:"ml-7"%>
  </div>

  <div class="my-3">
    <%= form.label :投稿する画像を選択してください, class:"bg-dark text-white"%>
    <%= form.label :必須, class:"badge badge-danger" %><br/>
    <%= form.file_field :image %>
    <div id="image-list"></div>
  </div>

  <div class="my-3">
    <%= form.label :出来事, class:"bg-dark text-white"%>
    <%= form.label :必須, class:"badge badge-danger" %><br/>
    <%= form.text_area :text, placeholder: "例）今日は名古屋ダイヤモンドドルフィンズの試合観戦！家族で大盛りあがり!最後にはなんと......", rows: "3", class:"form-control"%>
  </div>

  <div class="my-3">
    <%= form.label :チーム選択, class:"bg-dark text-white"%>
      <%= form.label :必須, class:"badge badge-danger" %><br/>
      <%= form.collection_select(:team_id, Team.all, :id, :name,{}) %><br />
  </div> 

  <div class="mb-4">
    <%= form.submit "投稿する", class:"btn btn-primary" %>
  </div>

</div>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'BaskeApp', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to '新規登録', new_user_registration_path, class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'ログイン', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>


        <li class="nav-item">
          <%=link_to "コミュニケーション", chat_home_index_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%=link_to "交換", items_path, class:"nav-link"%>
        </li>

        <li class="nav-item">
          <%=link_to "Bリーグ", "https://www.bleague.jp/", class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'バスケ検定', other_home_index_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <a href="https://lin.ee/pHke6nm"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
        </li>

        

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>

app/views/shared/_tweet.html.erb
<div class="card tweet-card mx-auto">
  <div class="card-img-top">
    <%= link_to discussion_tweet_path(tweet.id)  do %>
      <%= image_tag tweet.image, class:"img-fluid tweet-image py-1 px-1 my-1 ", size: "150x150" %>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= tweet.name%></h5>
    <p class="card-text"><%= tweet.text %></p>
    <p class="card-text"><%= tweet.team.name%></p>
    <span>投稿者</span><%= link_to "#{tweet.user.nickname}", user_path(tweet.user.id) %>
  </div>
</div>