config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root  'home#index'
  
  resources :home, only:[:index] do
    collection do
      get 'chat', 'other'
    end
  end

  resources :users, only:[:show]
  
  resources :tweets do
    member do
      get 'discussion'
    end
    resources :tweet_comments, only: [:create]
  end
  
  resources :items, only:[:index]
  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'シューズ' },
    { id: 3, name: 'バスケットウェアー'},
    { id: 4, name: 'ソックス'},
    { id: 5, name: 'トレーニングウェアー'},
    { id: 6, name: 'Bリーググッズ'},
    { id: 7, name: 'NBAグッズ'},
    { id: 8, name: 'レフリー'},
    { id: 9, name: 'ボール' },
    { id: 10, name: 'コート用品'},
    { id: 11, name: 'バッグ'},
    { id: 12, name: 'アクセサリー・グッズ'},
    { id: 13, name: 'インナーウェアー'},
    { id: 14, name: 'サポーター' },
    { id: 15, name: 'テーピング'},
    { id: 16, name: 'アイシンググッズ'},
    { id: 17, name: 'トレーニング用品'},
  ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
end

app/models/number_of_day.rb
class NumberOfDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1〜2日で発送' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '4〜7日で発送' }
  ]
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/sender_area.rb
class SenderArea < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品、未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '秋田ノーザンハピネッツ', image: 'image/about01_02.png' },
    { id: 3, name: '横浜ビー・コルセアーズ', image: 'image/fl_club_primary.png' },
    { id: 4, name: '新潟アルビレックスBB',image: 'image/img_flag.gif' },
    { id: 5, name: '富山グラウジーズ',image: 'image/富山.png' },
    { id: 6, name: 'レバンガ北海道',image: 'image/square_levanga_logo.png' },
    { id: 7, name: '宇都宮ブレックス',image: 'image/ph00162920.png' },
    { id: 8, name: '千葉ジェッツ',image: 'image/chibajets_logo_2018-01.png' },
    { id: 9, name: 'アルバルク東京',image: 'image/alvark.png' },
    { id: 10, name: 'サンロッカーズ渋谷',image: 'image/sr.png' },
    { id: 11, name: '川崎ブレイブサンダース',image: 'image/201807022050_2-600x0.png' },
    { id: 12, name: '三遠ネオフェニックス',image: 'image/_____________.png' },
    { id: 13, name: '滋賀レイクスターズ',image: 'image/logo.png' },
    { id: 14, name: '京都ハンナリーズ',image: 'image/京都.jpg' },
    { id: 15, name: '大阪エヴェッサ',image: 'image/8FEcLku_.png' },
    { id: 16, name: '琉球ゴールデンキングス',image: 'image/rg.png' },
    { id: 17, name: '信州ブレイブウォリアーズ',image: 'image/FPfXFwON_400x400.png' },
    { id: 18, name: '島根スサノオマジック',image: 'image/島根.jpeg' },
    { id: 19, name: '広島ドラゴンフライズ',image: 'image/広島.png' },
    { id: 20, name: 'シーホース三河',image: 'image/三河.png' },
    { id: 21, name: '名古屋ダイヤモンドドルフィンズ',image: 'image/team-logo01.png' },
    { id: 22, name: 'その他' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  has_one_attached :image
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy

  with_options presence: true do
    validates :name,   length: { maximum: 20 } 
    validates :image
    validates :text,   length: { maximum: 300 }    
    validates :team_id, numericality:{ other_than: 1, message: "を選択してください" }
  end

end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def remember_me
    true
  end
  
  has_many :items
  has_many :tweet_comments
  has_many :item_comments
  has_many :orders
  belongs_to_active_hash :team

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字混合で入力してください" }

  with_options presence: true do
    validates :nickname
    validates :phone, format: { with: /\A\d{10,11}\z/, message: "を半角数字のみ(10文字から11文字)で入力してください" }
    validates :full_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を全角で入力してください" }
    validates :full_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "を全角（カナ）で入力してください" }
    validates :birth_day
    validates :sex
    validates :team_id, numericality: { other_than: 1, message: "を選択してください" }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def other
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.all
  end

  def new
    @item = Item.new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/chat.html.erb
<%= render 'shared/header'%>
<div class="main">
    <h1>参加するチャットルームを選択してください</h1>
    <p>画像をクリックするとページが切り替わります</p>
    <div class="d-flex align-content-around flex-wrap">
      <% @teams.each do |team| %>
        <%= link_to tweet_path(team.id) do %>
        <%= image_tag "#{team.image}", class:"img-fluid", size:"200x200" %>
        <% end %>
      <% end %>
    </div>
</div>
<%= render 'shared/footer'%>

 

app/views/home/index.html.erb
<%= render 'shared/header' %>
  <div class="main">
    <div class="py-5">
      <h4><span>いくぜ！！</span>オリンピックバスケ開催</h4>
      <p class="timer h1">あと<span id="day"></span>日<span id="hour"></span>時間<span id="min"></span>分<span id="sec"></span>秒</p>
    </div>
    <div class="py-5">
      <div class="py-3">
        <%= link_to  '掲示板',chat_home_index_path, class:"btn btn-warning rounded-circle p-2" %>
      </div>
      <div class="py-3">  
        <%= link_to '交換', items_path, class:"btn btn-success rounded-circle p-2" %>
      </div>
      <div class="py-3">  
        <%= link_to 'バスケ検定', other_home_index_path, class:"btn btn-warning rounded-circle p-2" %>
      </div>
      <div class="py-3">
      <a href="https://lin.ee/pHke6nm"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="36" border="0"></a>
      </div>
    </div>
  </div>
<%= render 'shared/footer' %>

<script>
  'use strict';

  function countdown(due) {
    const now = new Date();

    const rest = due.getTime() - now.getTime();
    const sec = Math.floor(rest / 1000) % 60;
    const min = Math.floor(rest / 1000 / 60) % 60;
    const hours = Math.floor(rest / 1000 / 60 / 60) % 24;
    const days = Math.floor(rest / 1000 / 60 / 60 / 24);
    const count = [days, hours, min, sec];

    return count;
}


function recalc(){
  const counter = countdown(goal);
  document.getElementById('day').textContent = counter[0];
  document.getElementById('hour').textContent = counter[1];
  document.getElementById('min').textContent = String(counter[2]).padStart(2, '0');
  document.getElementById('sec').textContent = String(counter[3]).padStart(2, '0');
  refresh();
}

function refresh(){
  setTimeout(recalc, 1000);
}

let goal = new Date(2021, 7, 25);
recalc();

</script>

app/views/home/other.html.erb
<%= render 'shared/header' %>
<h1 class="mx-auto mt-5 h1 bg-warning">🏀バスケットボール検定🏀</h1>
<div id="text_q" class="mx-auto my-auto h4 bg-dark text-white"></div>
<div id="text_s" class="mx-auto my-auto"></div>
<h2 class="mx-auto my-auto bg-dark text-white">前の問題の答え</h2>
<div id="text_a" class="mx-auto my-auto h4"></div>

<script type="text/javascript">

qa = new Array();
    qa[0] = ["バスケットの神様と呼ばれるNBA史上最高の選手は？","レブロン・ジェームス","コービー・ブライアント","ケビン・ガーネット","マイケル・ジョーダン",4];
    qa[1] = ["日本人初となるNBAドラフト1巡目指名された八村塁選手ですが、どのチームから指名されたでしょうか？","ワシントン・ウィザーズ","ロサンゼルス・レイカーズ","クリーブラント・キャバリアーズ","ヒューストン・ロケッツ",1];
    qa[2] = ["Bリーグ初年度の優勝チームは？","宇都宮ブレックス","アルバルク東京","川崎ブレイブサンダース","名古屋ダイヤモンドドルフィンズ",1];
    qa[3] = ["Bリーグ初年度のMVPは？","田中大貴","富樫勇樹","ニック・ファジーカス","八村塁", 3];
    qa[4] = ["この中でNBAのチームに在籍していたことがない選手は？","ライアン・ロシター","ジョシュ・ハレルソン","ニック・ファジーカス","田臥勇太",1];
    qa[5] = ["比江島慎の身長は？","188cm","190cm","192cm","195cm",2];
    qa[6] = ["B1リーグのチーム数は？","15","20","25","30",2];
    qa[7] = ["B2リーグのチーム数は？","12","14","16","20",3];
    qa[8] = ["名古屋ダイヤモンドドルフィンズの1マスコットの名前は？","ドルちゃん","ブラックマンバ","エドワード","ディー・ディー",4];
    qa[9] = ["斎藤拓実の出身校として誤っているものは？","桐光学園高校","明治大学","白鳥中学","福岡第一高校",4];

    q_sel = 4;
    q_max = 10;
    setReady();

    function setReady(){
      count = 0;
      answers = new Array();
      randoms = new Array();
      quiz();
    };

    function getRandom(){
      let random_1 = Math.floor(Math.random()*10)
      if(!(randoms.includes(random_1))){
        randoms.push(random_1);
        return random_1;
      }else{
        let random_2 = random_1;
        while(randoms.includes(random_2)){ 
          let random_2 = Math.floor(Math.random()*10)
          if(!(randoms.includes(random_2))){
            randoms.push(random_2);
            console.log(randoms);
            return random_2;
          }
        }
      }
    }

    function quiz(){
      let s;
      let n;
      random = getRandom();
      document.getElementById("text_q").innerHTML = "第"+(count+1)+"問🏀"+qa[random][0];
      s = "";
      for(n=1; n<=q_sel; n++){
        if(qa[random][n] != ""){
          s += "<a href='javascript:answer(" + n + ")' class='choice text-warning h3'>" + n + "：" + qa[random][n] + "</a>";
        }
      }
      document.getElementById("text_s").innerHTML = s;
    };

    function answer(num){
      let s;
      s = (count+ 1)+"問目：";
      if(num === qa[random][q_sel+1]){
        answers[count] = "○";
      }else{
        answers[count] = "✗";
      }
      s += answers[count]+qa[random][num];
      document.getElementById("text_a").innerHTML = s;

      count++;
      if(count<q_max){
        quiz();
      }else{
        s = "<table border='2'><caption>成績発表</caption>";
        s += "<tr><th>問題</th>";
        for(n=0; n<qa.length; n++){
          s += "<th>"+(n+1)+"</th>";
        }
        s += "</tr>";
        s += "<tr><th>成績</th>";
        for(n=0; n<qa.length; n++){
          s += "<td>" + answers[n] + "</td>";
        }
        s += "</tr>";
        s += "</table>";
        document.getElementById("text_q").innerHTML = s;

        s = "【<a href='javascript:history.back()'>前のページに戻る</a>】";
        s += "【<a href='javascript:setReady()'>同じ問題を最初から</a>】";
        // s += "【<a href=">次の問題に進む</a>】";
        document.getElementById("text_s").innerHTML = s;
      }
    };

</script>