config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root  'home#index'
  
  resources :home, only:[:index] do
    collection do
      get 'chat', 'other'
    end
  end

  resources :users, only:[:show]
  
  resources :tweets do
    member do
      get 'discussion'
    end
    resources :tweet_comments, only: [:create]
  end
  
  resources :items, only:[:index]
  
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---'},
    { id: 2, name: 'シューズ' },
    { id: 3, name: 'バスケットウェアー'},
    { id: 4, name: 'ソックス'},
    { id: 5, name: 'トレーニングウェアー'},
    { id: 6, name: 'Bリーググッズ'},
    { id: 7, name: 'NBAグッズ'},
    { id: 8, name: 'レフリー'},
    { id: 9, name: 'ボール' },
    { id: 10, name: 'コート用品'},
    { id: 11, name: 'バッグ'},
    { id: 12, name: 'アクセサリー・グッズ'},
    { id: 13, name: 'インナーウェアー'},
    { id: 14, name: 'サポーター' },
    { id: 15, name: 'テーピング'},
    { id: 16, name: 'アイシンググッズ'},
    { id: 17, name: 'トレーニング用品'},
  ]
end

app/models/delivery_fee.rb
class DeliveryFee < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '着払い（購入者負担）' },
    { id: 3, name: '送料込み（出品者負担）' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/item_comment.rb
class ItemComment < ApplicationRecord
end

app/models/number_of_day.rb
class NumberOfDay < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '1〜2日で発送' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '4〜7日で発送' }
  ]
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/sender_area.rb
class SenderArea < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '新品、未使用' },
    { id: 3, name: '未使用に近い' },
    { id: 4, name: '目立った傷や汚れなし' },
    { id: 5, name: 'やや傷や汚れあり' },
    { id: 6, name: '傷や汚れあり' },
    { id: 7, name: '全体的に状態が悪い' }
  ]
end

app/models/team.rb
class Team < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '秋田ノーザンハピネッツ', image: 'image/about01_02.png' },
    { id: 3, name: '横浜ビー・コルセアーズ', image: 'image/fl_club_primary.png' },
    { id: 4, name: '新潟アルビレックスBB',image: 'image/img_flag.gif' },
    { id: 5, name: '富山グラウジーズ',image: 'image/富山.png' },
    { id: 6, name: 'レバンガ北海道',image: 'image/square_levanga_logo.png' },
    { id: 7, name: '宇都宮ブレックス',image: 'image/ph00162920.png' },
    { id: 8, name: '千葉ジェッツ',image: 'image/chibajets_logo_2018-01.png' },
    { id: 9, name: 'アルバルク東京',image: 'image/alvark.png' },
    { id: 10, name: 'サンロッカーズ渋谷',image: 'image/sr.png' },
    { id: 11, name: '川崎ブレイブサンダース',image: 'image/201807022050_2-600x0.png' },
    { id: 12, name: '三遠ネオフェニックス',image: 'image/_____________.png' },
    { id: 13, name: '滋賀レイクスターズ',image: 'image/logo.png' },
    { id: 14, name: '京都ハンナリーズ',image: 'image/京都.jpg' },
    { id: 15, name: '大阪エヴェッサ',image: 'image/8FEcLku_.png' },
    { id: 16, name: '琉球ゴールデンキングス',image: 'image/rg.png' },
    { id: 17, name: '信州ブレイブウォリアーズ',image: 'image/FPfXFwON_400x400.png' },
    { id: 18, name: '島根スサノオマジック',image: 'image/島根.jpeg' },
    { id: 19, name: '広島ドラゴンフライズ',image: 'image/広島.png' },
    { id: 20, name: 'シーホース三河',image: 'image/三河.png' },
    { id: 21, name: '名古屋ダイヤモンドドルフィンズ',image: 'image/team-logo01.png' },
    { id: 22, name: 'その他' }
  ]
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :team
  has_one_attached :image
  belongs_to :user
  has_many :tweet_comments, dependent: :destroy

  with_options presence: true do
    validates :name,   length: { maximum: 20 } 
    validates :image
    validates :text,   length: { maximum: 300 }    
    validates :team_id, numericality:{ other_than: 1, message: "を選択してください" }
  end

end

app/models/tweet_comment.rb
class TweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def remember_me
    true
  end
  
  has_many :items
  has_many :tweet_comments
  has_many :item_comments
  has_many :orders
  belongs_to_active_hash :team

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "は半角英数字混合で入力してください" }

  with_options presence: true do
    validates :nickname
    validates :phone, format: { with: /\A\d{10,11}\z/, message: "を半角数字のみ(10文字から11文字)で入力してください" }
    validates :full_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を全角で入力してください" }
    validates :full_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "を全角（カナ）で入力してください" }
    validates :birth_day
    validates :sex
    validates :team_id, numericality: { other_than: 1, message: "を選択してください" }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def chat
    @tweets = Tweet.all
    @teams = Team.all
  end

  def other
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.all
  end

  def new
    @item = Item.new
  end

  def create
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create]

  def show
    @team = Team.find(params[:id])
    @tweets = Tweet.where(team_id: @team.id)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else 
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    if @tweet.valid?
      @tweet.save
      redirect_to tweet_path(@tweet.team_id)
    else
      render :edite
    end
  end


  def destroy 
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
  end
  
  def discussion
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new
    @tweet_comments = TweetComment.where(tweet_id: @tweet.id)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:name, :image, :text, :team_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<%= render 'shared/header' %>
  <button type="button" class=" exchange btn btn-outline-warning">
    <%=link_to  new_item_path do %>
      <%= image_tag 'image/出品.png' , size: '50x50' %>
      <div style="text-decoration: none; color: black;"> 出品 </div>
    <% end %>
  </button>
<%= render 'shared/footer'%>

app/views/items/new.html.erb
<%= render 'shared/header'%>
<div class="main">
  <div class="container listing">
    <%= form_with(model: @item, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
      <div class="form-group">

        <div class="my-3">
          <%= f.label :商品名, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.text_field :name, placeholder: "例）バスケットボール", class:"ml-7"%>
        </div>

        <div class="my-3">
          <%= f.label :紹介文, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.text_field :name, placeholder: "例）学生の頃に使用していたボールです。就職してなかなかバスケットをすること
          なくなったので譲りたいと思います。", class:"ml-7"%>
        </div>
        
        <div class="my-3">
          <%= f.label :商品のカテゴリー, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, class:"ml-7") %>
        </div>
        
        <div class="my-3">
          <%= f.label :商品の状態, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.collection_select(:status_id, Status.all, :id, :name, {}, class:"ml-7") %>
        </div>
        
        <div class="my-3">
          <%= f.label :配送料, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.collection_select(:sender_area_id, DeliveryFee.all, :id, :name, {}, class:"ml-7") %>
        </div>
        
        <div class="my-3">
          <%= f.label :発送地, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.collection_select(:sender_area_id, SenderArea.all, :id, :name, {}, class:"ml-7") %>
        </div>
        
        <div class="my-3">
          <%= f.label :発送までの日数, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= f.collection_select(:number_of_day_id, NumberOfDay.all, :id, :name, {}, class:"ml-7") %>
        </div>
        
        <div class="my-3">
          <%= f.label :金額, class:"bg-dark text-white"%>
          <%= f.label :必須, class:"badge badge-danger" %><br/>
          <%= text_field :money, id:"item-money", placeholder:"例）1000円", class:"ml-7"%>
        </div>
        <div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
              <span id='profit'></span>円
          </div>
        </div>
        <button type="submit" class="btn btn-primary">出品する</button>

      </div>
    <% end %>
   </div>
</div>

app/views/tweets/destroy.html.erb
<%= render 'shared/header'%>
<div class="main">
    <div class="destroy">
        <h3 class="px-5 py-5 mx-5 mx-5 my-5 bg-danger text-white">削除が完了しました。</h3>
        <%= link_to '投稿一覧へ戻る', tweet_path(@tweet.id), class:"p-3 mb-2 bg-secondary text-white" %>
    </div>
</div>

<%= render 'shared/footer'%>

app/views/tweets/discussion.html.erb
<%= render 'shared/header'%>
<div class="main">
  <div>
    <%= render partial: "shared/tweet", locals:{tweet: @tweet} %>
    <div class="user-only">
      <% if user_signed_in? %>
        <% if current_user.id == @tweet.user_id%>
          <%= link_to '投稿の編集', edit_tweet_path(@tweet.id), class:"p-3 mb-2 bg-success text-white"%>
          <%= link_to '投稿の削除', tweet_path(@tweet.id), method: :delete, class:"p-3 mb-2 bg-danger text-white" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="comment mx-5">
    <% if current_user %>
      <%= form_with(model: [@tweet, @tweet_comment], local: true) do |f| %>
        <%= f.text_area :text, placeholder: "コメントする", rows:"2", class:"form-control" %>
        <%= f.submit "コメント", class:"btn btn-secondary" %>
      <% end %>
    <% end %>

    <% if @tweet_comments %>
      <% @tweet_comments.each do |tweet_comment| %>
        <div>
          <strong><%= link_to tweet_comment.user.nickname, user_path(tweet_comment.user.id) %>
          <%= tweet_comment.text %>
          <%= tweet_comment.created_at %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tweets/edit.html.erb
<%= render 'shared/header'%>
<div class="main">
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |form| %>
     <%= render partial: "shared/form", locals: { form: form } %>
   <% end %>
 </div>
</div>
<%= render 'shared/footer'%>

app/views/tweets/new.html.erb
<%= render 'shared/header'%>
<div class="main">
 <div class="container">
   <%= form_with(model: @tweet, local: true) do |form| %>
     <%= render 'shared/error_messages', model: form.object %>
     <%= render partial: "shared/form", locals: { form: form } %>
   <% end %>
 </div>
</div>

app/views/tweets/show.html.erb
<%= render 'shared/header'%>
<div class="main">
  <div class="my-3 mx-3 d-flex justify-content-end">
    <%= link_to "投稿する", new_tweet_path, class:"btn btn-primary", style:"position: fixed;" %>
  </div>

  <div>
    <div class="team-logo">
      <%= image_tag "#{@team.image}", class:"img-fluid", size:"250x250" %>
    </div>

    <div class="t">
      <% @tweets.each do |tweet| %>
        <%= render partial: 'shared/tweet',locals:{tweet:tweet} %>
      <% end %>
    </div>
  </div>
</div>


<%= render 'shared/footer'%>

app/views/users/show.html.erb
<div>
  <div><%= @user.nickname %></div>
  <div><%= @user.full_name %></div>
  <div><%= @user.full_name_kana %></div>
  <div><%= @user.birth_day %></div>
  <div><%= @user.team.name %></div>
  <% @tweets.each do |tweet| %>
    <%= image_tag tweet.image, class:"img-fluid" %>
    <p><%= tweet.name %></p>
    <p><%= tweet.text %></p>
  <% end %>
</div>